version: '3.8'

services:
  mlflow_client:
    build: .
    container_name: mlflow_client
    ports:
      - "8000:8000"
    volumes:
      - ../own_model/emotion.db:/mlflow_client/../own_model/emotion.db
      - ../own_model/mlruns:/mlflow_client/../own_model/mlruns          
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///../own_model/emotion.db
